# Generated by Django 5.2.4 on 2025-07-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_momo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momo',
            old_name='Category',
            new_name='category',
        ),
    ]
