# Generated by Django 5.2.4 on 2025-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_category_momo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='momo',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
