# Generated by Django 5.2.4 on 2025-09-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminEmail',
        ),
    ]
